cors:
  originPatterns: https://localhost:8080,http://localhost:5173
spring:
  application:
    name: "Voz Cidad√£"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/voz-cidada
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google.client-id: 518788781560-5kjacjm9okd3cnofcs2beq2e6nb7br12.apps.googleusercontent.com
          google.client-secret: ${GOOGLE_CLIENT_SECRET}
          google.scope:
            - profile
            - email
springdoc:
  swagger-ui:
    url: /openapi.yml
security:
  token:
    secret: ${JWT_SECRET:default-secret}
    expire-length: 3600
server:
  port: 8080
app:
  upload:
    dir: "/app/uploads"